name: lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install linters
      run: |
        sudo apt-get install -y npm
        npm install eslint --save-dev
        npm install stylelint --save-dev
        npm install htmlhint --save-dev
    - name: lint
      run: ./build.sh lint

